const mapAddress = encodeURIComponent("Medical Chowk, Ramdaiya Bhawadi-1, Janakpur Dham, Dhanusha, Nepal");

export interface EVModelData {
  id: string;
  name: string;
  brand: string;
  batteryCapacity: number; // kWh
  connector: "GB/T" | "CCS2";
  maxDcPower: number; // kW
  estimatedTime20to80: string; // mins
}

export const siteData = {
  businessName: "Aayush EV",
  alternateNames: [
    "Ayush Ev",
    "Ayush EV",
    "Ayush EV Janakpur",
    "Aayush EV Charging Station",
    "Ayush EV Charging Station Janakpur",
    "Aayush EV Charging Janakpur",
    "Ayush Charging Janakpur",
    "Aayush Car Wash & Servicing",
    "आयुष ईभी",
    "जनकपुर ईभी चार्जिङ",
    "रामदैया ईभी चार्जिङ स्टेशन",
  ],
  tagline: "120kW DC Fast Charging • Car Wash • Vehicle Servicing",
  description:
    "Aayush EV (Ayush EV) is Janakpur Dham's premier DC Fast EV Charging Station at Medical Chowk, Ramdaiya Bhawadi-1. Equipped with 120kW GB/T & 80kW CCS2 chargers supporting 4 vehicles simultaneously, plus car wash and servicing.",
  shortDescription:
    "Fast EV charging station in Janakpur Dham with 120kW GB/T & 80kW CCS2 DC fast chargers, car wash and vehicle servicing.",
  address: {
    street: "Medical Chowk",
    area: "Ramdaiya Bhawadi-1",
    city: "Janakpur Dham",
    state: "Dhanusha",
    province: "Madhesh Pradesh",
    postalCode: "45600",
    country: "Nepal",
    full: "Medical Chowk, Ramdaiya Bhawadi-1, Janakpur Dham, Dhanusha, Nepal",
  },
  geo: {
    latitude: 26.7865,
    longitude: 85.9320,
    region: "NP-P2",
    placename: "Janakpur Dham, Dhanusha, Nepal",
  },
  phone: "+977 9714099611",
  rawPhone: "+9779714099611",
  whatsapp: "https://wa.me/9779714099611",
  openingHours: {
    display: "Call administration for opening hours & 24/7 emergency charging",
    days: "Monday - Sunday (7 Days a week)",
    statusText: "Active DC Fast Charging Available",
    weekly: [] as { open: number; close: number }[],
  },
  location: {
    nearbyLandmark: "Medical Chowk",
    corridor: "Janakpur-Dhalkebar Highway Corridor (Ramdaiya Bhawadi-1)",
    mapEmbedUrl: `https://www.google.com/maps?q=${mapAddress}&output=embed`,
    directionsUrl: `https://www.google.com/maps/dir/?api=1&destination=${mapAddress}`,
  },
  chargers: [
    {
      id: "dc-fast-1",
      type: "DC Ultra Fast Charger",
      power: "120 kW",
      connector: "GB/T",
      count: "1 Point (Dual Gun / Multi-Vehicle)",
      description: "Ultra-fast DC charging optimized for GB/T compatible electric vehicles.",
    },
    {
      id: "dc-ccs2-80",
      type: "DC Fast Charger",
      power: "80 kW",
      connector: "CCS2",
      count: "1 Point (Dual Gun / Multi-Vehicle)",
      description: "High-speed DC charging for international European & Indian CCS2 standard EVs.",
    },
  ],
  pricing: {
    ratePerKwh: "Rs 16.50",
    unit: "per kWh",
    rates: [
      {
        type: "120 kW · GB/T DC Fast",
        rate: "Rs 16.50",
        unit: "per kWh",
      },
      {
        type: "80 kW · CCS2 DC Fast",
        rate: "Rs 16.50",
        unit: "per kWh",
      },
    ],
    note: "Both chargers cost Rs 16.50 per kWh. Charging by battery percentage is priced according to vehicle model and battery capacity. Call administration to confirm your model’s rate before charging.",
  },
  facilities: [
    { name: "120kW & 80kW DC Charging", icon: "charging", desc: "Ultra fast DC dual-gun charging stations" },
    { name: "Car Wash", icon: "washroom", desc: "High-pressure foam wash and exterior cleaning" },
    { name: "Vehicle Servicing", icon: "service", desc: "General checkup, tire pressure and EV maintenance" },
    { name: "4 Vehicles at Once", icon: "parking", desc: "Simultaneous charging bays for quick turnaround" },
  ],
  amenitiesList: [
    "120kW GB/T DC Fast Charger",
    "80kW CCS2 DC Fast Charger",
    "Simultaneous 4-Vehicle Charging Bays",
    "Professional Car Wash Center",
    "EV Vehicle Servicing & Inspection",
    "Driver Rest & Waiting Area",
    "Clean Washrooms & Restrooms",
    "Nearby Medical Chowk Cafes & Tea Stalls",
    "24/7 Phone Support & Route Assistance",
    "Digital Payments (eSewa, Khalti, Fonepay, Cash)",
  ],
  paymentMethods: ["Cash", "Fonepay / QR", "eSewa", "Khalti", "Mobile Banking"],
  bookingUrl: "",
  supportedVehicles: "Electric vehicles with compatible GB/T or CCS2 connectors (BYD, Tata, MG, Hyundai, Deepal, Omoda, Seres, Neta, Mahindra, Kia, Tesla & more)",
  
  // Popular EV Models in Nepal for the interactive calculator and AEO keyword matching
  popularEvModels: [
    {
      id: "byd-atto-3",
      brand: "BYD",
      name: "BYD Atto 3 (60.48 kWh)",
      batteryCapacity: 60.48,
      connector: "GB/T",
      maxDcPower: 88,
      estimatedTime20to80: "35-45 mins",
    },
    {
      id: "byd-dolphin",
      brand: "BYD",
      name: "BYD Dolphin (44.9 kWh)",
      batteryCapacity: 44.9,
      connector: "GB/T",
      maxDcPower: 60,
      estimatedTime20to80: "30-40 mins",
    },
    {
      id: "byd-seal",
      brand: "BYD",
      name: "BYD Seal (82.5 kWh)",
      batteryCapacity: 82.5,
      connector: "GB/T",
      maxDcPower: 120,
      estimatedTime20to80: "30-40 mins",
    },
    {
      id: "tata-nexon-ev-long",
      brand: "Tata",
      name: "Tata Nexon EV Long Range (40.5 kWh)",
      batteryCapacity: 40.5,
      connector: "CCS2",
      maxDcPower: 50,
      estimatedTime20to80: "40-50 mins",
    },
    {
      id: "tata-tiago-ev",
      brand: "Tata",
      name: "Tata Tiago EV (24 kWh)",
      batteryCapacity: 24.0,
      connector: "CCS2",
      maxDcPower: 30,
      estimatedTime20to80: "35-45 mins",
    },
    {
      id: "tata-punch-ev",
      brand: "Tata",
      name: "Tata Punch EV (35 kWh)",
      batteryCapacity: 35.0,
      connector: "CCS2",
      maxDcPower: 50,
      estimatedTime20to80: "35-45 mins",
    },
    {
      id: "mg-zs-ev",
      brand: "MG",
      name: "MG ZS EV (51.1 kWh)",
      batteryCapacity: 51.1,
      connector: "CCS2",
      maxDcPower: 80,
      estimatedTime20to80: "35-45 mins",
    },
    {
      id: "mg-comet-ev",
      brand: "MG",
      name: "MG Comet EV (17.3 kWh)",
      batteryCapacity: 17.3,
      connector: "GB/T",
      maxDcPower: 15,
      estimatedTime20to80: "45-55 mins",
    },
    {
      id: "hyundai-ioniq-5",
      brand: "Hyundai",
      name: "Hyundai Ioniq 5 (72.6 kWh)",
      batteryCapacity: 72.6,
      connector: "CCS2",
      maxDcPower: 120,
      estimatedTime20to80: "25-35 mins",
    },
    {
      id: "hyundai-kona-ev",
      brand: "Hyundai",
      name: "Hyundai Kona Electric (39.2 kWh)",
      batteryCapacity: 39.2,
      connector: "CCS2",
      maxDcPower: 50,
      estimatedTime20to80: "40-50 mins",
    },
    {
      id: "deepal-s07",
      brand: "Deepal",
      name: "Deepal S07 (66.8 kWh)",
      batteryCapacity: 66.8,
      connector: "GB/T",
      maxDcPower: 90,
      estimatedTime20to80: "35-45 mins",
    },
    {
      id: "omoda-e5",
      brand: "Omoda",
      name: "Omoda E5 (61 kWh)",
      batteryCapacity: 61.0,
      connector: "CCS2",
      maxDcPower: 80,
      estimatedTime20to80: "35-45 mins",
    },
    {
      id: "neta-v",
      brand: "Neta",
      name: "Neta V / Neta Aya (38.5 kWh)",
      batteryCapacity: 38.5,
      connector: "GB/T",
      maxDcPower: 50,
      estimatedTime20to80: "35-45 mins",
    },
    {
      id: "seres-3",
      brand: "Seres",
      name: "Seres 3 EV (53.6 kWh)",
      batteryCapacity: 53.6,
      connector: "CCS2",
      maxDcPower: 60,
      estimatedTime20to80: "40-50 mins",
    },
    {
      id: "mahindra-xuv400",
      brand: "Mahindra",
      name: "Mahindra XUV400 EV (39.4 kWh)",
      batteryCapacity: 39.4,
      connector: "CCS2",
      maxDcPower: 50,
      estimatedTime20to80: "40-50 mins",
    },
  ] as const satisfies readonly EVModelData[],

  // 100+ Targeted SEO / AEO / GEO Keywords for Top Ranking in Nepal & Janakpur
  keywordMatrix: {
    primary: [
      "Ayush Ev",
      "Aayush EV",
      "ev charging janakpur",
      "charging janakpur",
      "ev charging station janakpur",
      "electric vehicle charging Janakpur",
      "Ayush EV Janakpur",
      "Aayush EV Janakpur",
    ],
    localGeo: [
      "Medical Chowk EV charging",
      "Ramdaiya Bhawadi EV station",
      "Ramdaiya Bhawadi-1 charging station",
      "Janakpur Dham EV fast charger",
      "Dhanusha EV charging station",
      "Madhesh Pradesh EV charger",
      "Janakpur-Dhalkebar highway EV charging",
      "Janakpur bypass EV charger",
      "EV charging near Janakpur railway station",
      "EV charging station near Janaki Mandir",
      "Mithila EV charging station",
      "Bardibas to Janakpur EV charging point",
      "Dhalkebar to Janakpur EV charging",
      "Jaleshwar Janakpur EV charging",
      "Sitamarhi Janakpur EV charging station",
    ],
    chargerSpecsAndSpeed: [
      "120kW DC fast charger Janakpur",
      "80kW DC fast charger Janakpur",
      "GB/T fast charger Nepal",
      "CCS2 fast charger Janakpur",
      "DC fast charging Janakpur Dham",
      "high speed EV charging Nepal",
      "4 vehicle simultaneous EV charging",
      "rapid EV charging Janakpur",
      "dual gun DC EV charger Nepal",
      "commercial EV charging station Dhanusha",
    ],
    vehicleSpecific: [
      "BYD Atto 3 charging Janakpur",
      "BYD Dolphin fast charger Janakpur",
      "BYD Seal charging station Janakpur",
      "BYD e6 charging Nepal",
      "Tata Nexon EV charging Janakpur",
      "Tata Tiago EV charger Janakpur",
      "Tata Punch EV charging Janakpur",
      "Tata Curvv EV charging Janakpur",
      "MG ZS EV charging station Janakpur",
      "MG Comet EV charging Janakpur",
      "Hyundai Ioniq 5 DC fast charger Janakpur",
      "Hyundai Kona EV charging Janakpur",
      "Deepal S07 fast charging Janakpur",
      "Omoda E5 EV charging Janakpur",
      "Neta V charging station Janakpur",
      "Seres 3 EV charging Janakpur",
      "Mahindra XUV400 EV charger Janakpur",
      "Kia EV6 charging Nepal",
      "Tesla GB/T CCS2 charging Janakpur",
    ],
    servicesAndPricing: [
      "EV charging cost per kWh Nepal",
      "EV charging rate Janakpur Rs 16.50",
      "EV charging by battery percentage rate Janakpur",
      "Car wash Janakpur Dham",
      "EV car wash Ramdaiya Bhawadi",
      "high pressure foam car wash Janakpur",
      "Electric car servicing Janakpur",
      "EV vehicle maintenance Dhanusha",
      "EV tire check and general servicing Janakpur",
      "24/7 EV emergency charging Janakpur",
    ],
    nepaliQueries: [
      "आयुष ईभी",
      "जनकपुर ईभी चार्जिङ",
      "जनकपुरमा गाडी चार्ज गर्ने ठाउँ",
      "फास्ट चार्जिङ जनकपुर",
      "रामदैया भवाडी ईभी चार्जिङ स्टेशन",
      "मेडिकल चोक जनकपुर ईभी चार्जर",
      "धनुषा ईभी चार्जिङ स्टेशन",
      "विद्युतीय सवारी साधन चार्जिङ जनकपुर",
    ],
  },
} as const;
